stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: blueforest/film:2.0.3
      pushRemote: true
      registry: index.docker.io
timeout: 60
